changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.spec.*"
  - "**/*{eslint,jest}*"
  - "**/*.{md,sh}"
  - "**/.DS_Store"
  - .github/**/*
  - .husky/**/*
  - scripts/**/*
  - .gitattributes
  - .gitignore
  - .yarnrc.yml
  - typedoc.*
  - .markdownlint.json

compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.0.1.cjs
