version: "3.9"

services:
  node:
    platform: linux/amd64
    image: archwaynetwork/archwayd:v0.2.0
    command: > 
      start --x-crisis-skip-assert-invariants
      && apt-get update
      && apt-get install -y curl
      docker-entrypoint.sh
    ports:
      - 1317:1317   # API
      - 9090:9090   # gRPC
      - 9091:9091   # gRPC-web
      - 26656:26656 # p2p
      - 26657:26657 # RPC
    volumes:
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./scripts:/
      - data:/root/.archway
    env_file:
      - local-node.env
      
volumes:
  data:
