version: "3.9"

services:
  node:
    platform: linux/amd64
    image: archwaynetwork/archwayd:v0.2.0
    network_mode: "host"
    command: start --x-crisis-skip-assert-invariants
    entrypoint: /docker-entrypoint.sh
    volumes:
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh
      - data:/root/.archway

volumes:
  data:
