services:
  node:
    image: archwaynetwork/archwayd:v0.4.0
    command: start --x-crisis-skip-assert-invariants
    entrypoint: /docker-entrypoint.sh
    ports:
      - 1317:1317   # API
      - 9090:9090   # gRPC
      - 9091:9091   # gRPC-web
      - 26656:26656 # p2p
      - 26657:26657 # RPC
    volumes:
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./scripts/contracts:/contracts:ro
      - data:/root/.archway
    environment:
      - VALIDATOR_MNEMONIC
      - GENESIS_ACCOUNTS=archway1ecak50zhujddqd639xw4ejghnyrrc6jlwnlgwt,

volumes:
  data:
