name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DEVX_MNEMONIC: '${{ secrets.DEVX_MNEMONIC }}'
      VALIDATOR_MNEMONIC: '${{ secrets.VALIDATOR_MNEMONIC }}'
      GENESIS_ACCOUNTS: '${{ secrets.GENESIS_ACCOUNTS }}'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1' 
      - run: pwd
      - run: mkdir -p scripts/tmp
      - run: git clone https://github.com/archway-network/archway.git
        working-directory: ./scripts/tmp
      - run: make install
        working-directory: ./scripts/tmp/archway      
      - run: npm install -g @archwayhq/cli
      - run: yarn install --immutable      
      - name: Start local node
        run: |
          VALIDATOR_MNEMONIC='${{ secrets.VALIDATOR_MNEMONIC }}' GENESIS_ACCOUNTS='${{ secrets.GENESIS_ACCOUNTS }}' docker compose -p proj-arch3js-node-1 -f docker-compose.yaml run --name arch3js-node-1 -T
        
          docker logs -f --details --until=20s arch3js-node-1  
      - run: docker ps      
      - run: docker exec -i arch3js-node-1 /bin/sh && curl -v -s "http://localhost:26657/block?height=1"
      - name: Deploy airdrop contract
        run: scripts/deploy-airdrop.sh
      - run: yarn test:all --passWithNoTests
