name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      ENTRYPOINT_OUTPUT: ""
      DEPLOYER_ACCOUNT_NAME: "archway1rev2n7edzn6l84k37dhnhs0m9wqlveezvwjj38"
      DEVX_MNEMONIC: '${{ secrets.DEVX_MNEMONIC }}'
      VALIDATOR_MNEMONIC: '${{ secrets.VALIDATOR_MNEMONIC }}'
      GENESIS_ACCOUNTS: "archway1rev2n7edzn6l84k37dhnhs0m9wqlveezvwjj38"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1' 
      - run: pwd
      - run: mkdir -p scripts/tools
      - run: git clone https://github.com/archway-network/archway.git
        working-directory: ./scripts/tools
      - run: make install
        working-directory: ./scripts/tools/archway      
      - run: npm install -g @archwayhq/cli
      - run: yarn install --immutable      
      - name: Start local node
        run: |
          file="local-node.env"
          echo "VALIDATOR_MNEMONIC='${{ secrets.VALIDATOR_MNEMONIC }}'" > $file
          echo "GENESIS_ACCOUNTS='${{ env.GENESIS_ACCOUNTS }}'" >> $file
          cat $file

          docker compose -f "docker-compose.yaml" up -d
      - name: Wait for local chain to start
        run: >
          set -euo pipefail &&
          curl --retry 15 -f --retry-all-errors --retry-delay 2 -s "http://localhost:26657/block?height=1" |
            jq '.error == null' && 
            echo "Node started" || {
              echo "Node failed to start."
              exit 1
            }
      - run: sudo apt-get install -y expect
      - run: scripts/create-account.sh
      - name: Deploy airdrop contract
        run: scripts/deploy-contract-gh.sh "${{ env.DEPLOYER_ACCOUNT_NAME }}"
     
