name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --immutable
      - name: Start local chain on docker
        run: docker compose -f "docker-compose.yaml" up -d --build
      - name: Wait for local chain to start
        run: >
          set -euo pipefail &&
          curl --retry 20 -f --retry-all-errors --retry-delay 1 -s "http://localhost:26657/block?height=1" |
            jq '.error == null' && 
            echo "Node started" || {
              echo "Node failed to start."
              exit 1
            }
      - run: yarn test:all --passWithNoTests
